### ISSUE TITLE
The Support Forum is often not available - what is the Reason?

### ISSUE THREAD

**Issue by AlexL777** [InfernoGroupUK/LayerBulletin#5]
Hi Developers,

Our support forum for LayerBulletin is very often not available. Are there really serious problems with web hosting or is it something basic?

Unfortunately, the activity around forum also dropped slightly and hardly a postet.

Very unfortunate, because I have nevertheless the Repo here forked, in order to pursue the development.

How does it actually work with the next version of the forum? 😺

**Comment by InfernoGroupUK** [comment]
Hello,

If you are relating to the forum located normally at LayerBulletin.com, then this has been taken offline.

This has been because there has been a lack of interest from any other developers to help continue with LayerBulletin.

LayerBulletin has been recently developed solely by myself, to which I can no longer commit any time into the project due to my working life style, there has been posts put on the forums as well as mass emails and other advertisements, discussions internally was on going as well to find another developer to which all failed.

LayerBulletin will still receive updates when it is needed and has not been completely forgotten, as for the actual website, the domain name is in the process of being renewed and will hopefully be available again shortly.

I can only apologise for the lack of communication, due to other work commitments.

**Comment by AlexL777** [comment]
Hi @InfernoGroupUK ,

Ok, no problem, thanks, that you at least report here. I like to follow LayerBulltin and try to keep my loyalty to your forum tool. Unfortunately, I can not program PHP. This is the only thing I am missing as the webuser. But programming is not easy.

Nevertheless, one should look ahead and perhaps the forum will one day be brought back to life. We'll see.

I hope your GitHub repo will continue.

Thanks in advance.

**Comment by InfernoGroupUK** [comment]
Hi @AlexL777 ,

The GitHub Repo will remain online and available for others to download and receive limited support for LayerBulletin.

LayerBulletin will also still receive updates from time to time when it is needed and/or reported as a bug.

Many Thanks,
Andy Rixon

**Comment by AlexL777** [comment]
Hi @InfernoGroupUK ,

that sounds good and I'm glad that the repo will be back. Thank you!

**Comment by InfernoGroupUK** [comment]
Hi @AlexL777 ,

After a little thought, LayerBulletin is no longer going to receive any updates at all, I have decided on a different approach and that is starting a fresh.

Please check out [LayerBB](https://www.layerbb.com), which is the future and is the new project which I am working on.

Many Thanks,
Andy Rixon

**Comment by AlexL777** [comment]
Hi Andy,

Your new project looks promising and I will gladly follow it. I am looking forward to seeing when the first RC version will be released or the final release!

Thanks for that. If your new forum appears, I certainly install it.

**Comment by InfernoGroupUK** [comment]
@AlexL777 ,

Feel free to register on the new forums.
